drop table if exists user CASCADE;
create table user (
    id bigint generated by default as identity,
    email varchar(255) unique ,
    password varchar(255),
    provider varchar(255),
    provider_id varchar(255),
    role varchar(255),
    name varchar(255),
    primary key (id)
 );
